server:
  port: 8081

spring:
  application:
    # 注册到 Eureka Server 的名称
    name: micro-provider-user
eureka:
  instance:
    # true 将自己ip注册到 Eureka Server上，false 将hostname注册到Eureka Server上，默认false
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 负载均衡配置
micro-provider-movie:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# feign 日志配置
logging:
  level:
    com.cloud.user.feign.MoviefeignClient: DEBUG

management:
  endpoint:
    health:
      show-details: always
