server:
  port: 8084

spring:
  profiles:
    active: db
  #basic 认证 账户密码
  security:
    user:
      name: admin
      password: admin
  application:
    # 注册到 Eureka Server 的名称
    name: micro-provider-shop
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
  instance:
    # true 将自己ip注册到 Eureka Server上，false 将hostname注册到Eureka Server上，默认false
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://152.136.190.118:9300/eureka/

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

