
server:
  port: 7970

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    # 注册到 Eureka Server 的名称
    name: TransactionManager
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        - id: movie
#            # lb代表从注册中心获取服务
          uri: lb://MICRO-PROVIDER-MOVIE
          predicates:
            - Path=/movie/**
          filters:
            - StripPrefix=0
        - id: user
          # lb代表从注册中心获取服务
          uri: lb://MICRO-PROVIDER-USER
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0

eureka:
  instance:
    # true 将自己ip注册到 Eureka Server上，false 将hostname注册到Eureka Server上，默认false
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://152.136.190.118:9300/eureka/

